# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings

pygments: true
safe: true
auto: true

title: 国际哥的独立博客
email: 752147916@qq.com
description: > # this means to ignore newlines until "baseurl:"
  写博虽易，建博不易，且写且珍惜
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: shaoguoji
github_username:  shaoguoji

# Build settings
markdown: kramdown
